**Data Mining With Human Mobility Data**

**Introduction**

This project attempts to use human mobility data to find Co-occurrence Patterns of Points of Interest. This can be used for tourism and to find co-relation between places.

In [1]:
# Imports

import pandas as pd
import numpy as np

In [24]:
df_cityB_POI = pd.read_csv("/workspaces/Machine-learning-projects/JapanDataMining/Data/POIdata_cityB.csv")
df_cityC_POI = pd.read_csv("/workspaces/Machine-learning-projects/JapanDataMining/Data/POIdata_cityC.csv")
df_cityD_POI = pd.read_csv("/workspaces/Machine-learning-projects/JapanDataMining/Data/POIdata_cityD.csv")

In [26]:
df_cityD_POI.head() # Sample look into how these data frames look

   x   y  category  POI_count
0  1  11        46          1
1  1  55        60          2
2  1  55        48          1
3  1  56        68          1
4  1  56        75          1

In [36]:
# Cleaning up the columns

df_categories = pd.read_csv("/workspaces/Machine-learning-projects/JapanDataMining/Data/POI_datacategories.csv",header=None)


df_categories.columns = ['category']
df_categories.reset_index(drop=False, inplace=True)
df_categories['category_name'] = df_categories['category']
df_categories.drop(columns=['category'],inplace=True)
df_categories.rename(columns={'index': 'category'}, inplace=True)

df_categories

    category        category_name
0          0                 Food
1          1             Shopping
2          2        Entertainment
3          3  Japanese restaurant
4          4   Western restaurant
..       ...                  ...
80        80       Heavy Industry
81        81                  NPO
82        82       Utility Copany
83        83                 Port
84        84    Research Facility

[85 rows x 2 columns]

**Grouping the data**

In [40]:
merged_df_D = pd.merge(df_cityD_POI, df_categories, on='category', how='left')
merged_df_D.head(10)

   x   y  category  POI_count         category_name
0  1  11        46          1                  Park
1  1  55        60          2           Post Office
2  1  55        48          1          Parking Area
3  1  56        68          1            Hair Salon
4  1  56        75          1     Accountant Office
5  1  56        41          1  Online Grocery Store
6  1  56        14          1      Creative cuisine
7  1  56        82          1        Utility Copany
8  1  56         3          1   Japanese restaurant
9  1  57        69          3         Lawyer Office